apiVersion: v1
kind: Service
metadata:
  name: portscan
spec:
  type: {{ .Values.portscan.service.type }}
  ports:
    - port: {{ .Values.portscan.service.port }}
      targetPort: 4000
  selector:
    app: portscan
