version: "3"
services:
  devcontainer:
    depends_on:
      - opensearch
    build: .
    command: sleep infinity
    networks:
      - portscan
    ports:
      - 4000:4000
    volumes:
      - ..:/workspace:cached
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - portscan

volumes:
  opensearch-data:

networks:
  portscan:
    driver: bridge
