version: "3"
services:
  devcontainer:
    depends_on:
      - opensearch
    build: .
    command: sleep infinity
    networks:
      - portscan
    ports:
      - 4000:4000
    volumes:
      - ..:/workspace:cached
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=OS2xTempPass1!"
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - portscan

volumes:
  opensearch-data:

networks:
  portscan:
    driver: bridge
